#邮件通知设置
spring:
  mail:
    host: smtp.163.com
    username: shoppisdfsdngkill@163.com
    password: TSVSsdfsdfsdsWNMMIHUDHUYY
    port: 25
    default-encoding: utf-8
    protocol: smtp

# 阿里云存储参数配置
ali:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAIoOIpViJsdfsOimve
    accessKeySecret: XzU1crrklFHsdfsdfslEHRgENojhew5b09hMC
    bucketName: shoppingkill
    url: //shsdfopisdfngksl.oss-cn-shenzhen.aliyuncs.com/
    aliUrl: http://shosdfpisdfsdngksdfill.oss-cn-shenzhen.aliyuncs.com/
    getFileUrl: ${aliyun.oss.url}${aliyun.oss.fileDir}
    myHostUrl:

#SMS榛子云参数配置
zzy:
  apiUrl: https://sms_developer.zhenzikj.com
  appSecret: MDAxNDZiNGdfsfsdfsdMtNTYwNy00ZTcwLWEyNTItMGY1OThmYmNjZGM2
  appId: 105924

jwt:
  redisToken: 4800
  expire: 3600
  newToken: 600
  keys: shoppingkill-sirwsl

verify:
  imgCodeTimeOut: 300
  phoneCodeTimeOut: 300

req:
  doMainUrl: url

url:
  image: http://
  webPage: http://
  server: http://

