#邮件通知设置
spring:
  mail:
    host: smtp.163.com
    username: shoppingkill@163.com
    password: TSVSWNMMIHUDHUYY
    port: 25
    default-encoding: utf-8
    protocol: smtp

# 阿里云存储参数配置
ali:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAIoOIpViJOimve
    accessKeySecret: XzU1crrklFHlEHRgENojhew5b09hMC
    bucketName: shoppingkill
    url: //shopingkill.oss-cn-shenzhen.aliyuncs.com/
    aliUrl: http://shopingkill.oss-cn-shenzhen.aliyuncs.com/
    getFileUrl: ${aliyun.oss.url}${aliyun.oss.fileDir}
    myHostUrl: http://static.wslhome.top/

#SMS榛子云参数配置
zzy:
  apiUrl: https://sms_developer.zhenzikj.com
  appSecret: MDAxNDZiNGMtNTYwNy00ZTcwLWEyNTItMGY1OThmYmNjZGM2
  appId: 105924

jwt:
  redisToken: 4800
  expire: 3600
  newToken: 600
  keys: wslhome-shoppingkill-sirwsl

verify:
  imgCodeTimeOut: 300
  phoneCodeTimeOut: 300

