# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8

# 应用名称
spring:
  application:
    name: shopping-kill
  # spring 静态资源扫描路径
  resources:
    static-locations: classpath:/static/
  #环境修改
  profiles:
    active: dev


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-8
    default-property-inclusion: non_null


jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379



